import {
  BabyIcon,
  BadgeCentIcon,
  BanknoteIcon,
  BookOpenIcon,
  BriefcaseBusinessIcon,
  Building2Icon,
  BusFrontIcon,
  CarIcon,
  CircleDotIcon,
  CircleEllipsisIcon,
  CirclePlusIcon,
  ClapperboardIcon,
  CoffeeIcon,
  CreditCardIcon,
  DumbbellIcon,
  EllipsisIcon,
  Gamepad2Icon,
  GiftIcon,
  HandHeartIcon,
  HandCoinsIcon,
  HeartPulseIcon,
  HouseIcon,
  LaptopIcon,
  LandmarkIcon,
  Music2Icon,
  PawPrintIcon,
  PlaneIcon,
  PiggyBankIcon,
  ReceiptTextIcon,
  Repeat2Icon,
  RotateCcwIcon,
  ShirtIcon,
  ShoppingBagIcon,
  ShieldCheckIcon,
  SmartphoneIcon,
  SparklesIcon,
  UtensilsIcon,
  UsersIcon,
  WalletCardsIcon,
  WalletIcon,
  WifiIcon,
  WrenchIcon,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  baby: BabyIcon,
  "badge-cent": BadgeCentIcon,
  banknote: BanknoteIcon,
  "book-open": BookOpenIcon,
  "briefcase-business": BriefcaseBusinessIcon,
  "building-2": Building2Icon,
  "bus-front": BusFrontIcon,
  car: CarIcon,
  "circle-dot": CircleDotIcon,
  "circle-ellipsis": CircleEllipsisIcon,
  "circle-plus": CirclePlusIcon,
  clapperboard: ClapperboardIcon,
  coffee: CoffeeIcon,
  "credit-card": CreditCardIcon,
  dumbbell: DumbbellIcon,
  ellipsis: EllipsisIcon,
  gift: GiftIcon,
  "gamepad-2": Gamepad2Icon,
  "hand-coins": HandCoinsIcon,
  "hand-heart": HandHeartIcon,
  "heart-pulse": HeartPulseIcon,
  house: HouseIcon,
  laptop: LaptopIcon,
  landmark: LandmarkIcon,
  "music-2": Music2Icon,
  "paw-print": PawPrintIcon,
  plane: PlaneIcon,
  "piggy-bank": PiggyBankIcon,
  "receipt-text": ReceiptTextIcon,
  "repeat-2": Repeat2Icon,
  "rotate-ccw": RotateCcwIcon,
  shirt: ShirtIcon,
  "shield-check": ShieldCheckIcon,
  "shopping-bag": ShoppingBagIcon,
  smartphone: SmartphoneIcon,
  sparkles: SparklesIcon,
  utensils: UtensilsIcon,
  users: UsersIcon,
  "wallet-cards": WalletCardsIcon,
  wallet: WalletIcon,
  wifi: WifiIcon,
  wrench: WrenchIcon,
};

export const categoryIconOptions = [
  { value: "circle-dot", label: "General" },
  { value: "house", label: "Housing" },
  { value: "utensils", label: "Food" },
  { value: "coffee", label: "Dining" },
  { value: "bus-front", label: "Transport" },
  { value: "car", label: "Car" },
  { value: "receipt-text", label: "Bills" },
  { value: "wifi", label: "Internet" },
  { value: "shopping-bag", label: "Shopping" },
  { value: "shirt", label: "Clothing" },
  { value: "heart-pulse", label: "Health" },
  { value: "dumbbell", label: "Fitness" },
  { value: "book-open", label: "Education" },
  { value: "paw-print", label: "Pets" },
  { value: "baby", label: "Children" },
  { value: "users", label: "Family" },
  { value: "hand-heart", label: "Giving" },
  { value: "clapperboard", label: "Entertainment" },
  { value: "gamepad-2", label: "Games" },
  { value: "music-2", label: "Music" },
  { value: "repeat-2", label: "Subscription" },
  { value: "plane", label: "Travel" },
  { value: "badge-cent", label: "Fees" },
  { value: "wrench", label: "Maintenance" },
  { value: "briefcase-business", label: "Salary" },
  { value: "laptop", label: "Freelance" },
  { value: "building-2", label: "Business" },
  { value: "sparkles", label: "Bonus" },
  { value: "gift", label: "Gift" },
  { value: "hand-coins", label: "Income" },
  { value: "shield-check", label: "Insurance" },
] as const;

export function getFinanceIcon(name: string): LucideIcon {
  return icons[name] ?? CircleDotIcon;
}

export function FinanceIcon({ name, className }: { name: string; className?: string }) {
  const Icon = getFinanceIcon(name);
  return <Icon aria-hidden="true" className={className} />;
}
